### ISSUE TITLE
Package name ideas

### ISSUE THREAD

**Issue by mitchelloharawild** [mitchelloharawild/mixtime#3]
The `{moment}` name isn't great due to its loading with `{distributional}` moments.

Unfortunately a `{CHRONOS}` package exists for Bioconductor, so that isn't an option. A better name is needed, discussion for that can occur here.

cc @GeorgeAthana @robjhyndman

**Comment by GeorgeAthana** [comment]
khronos, chronus are both correct spellings :-)

**Comment by GeorgeAthana** [comment]
and here is the sticker :-) 

https://www.amazon.com/Khronos-Diamond-Cluster-Bezel-Watch/dp/B0199APEKW

**Comment by alainaa** [comment]
flavours of time and tsibbles and R... tsimer :-)

**Comment by mitchelloharawild** [comment]
Some more ideas:
sundial, cuckoo, watch, pocketwatch, timely

**Comment by mitchelloharawild** [comment]
Some more names: ~~era~~, yonks, tempo

I think the important feature to convey in the title here is the mixed temporal granularities. I don't know of any brief terminology that can be used to describe this concept, so I'm left preferring abstract links to the idea - such as multiple hands on a clock.

**Comment by mitchelloharawild** [comment]
Renamed to mixtime, more directly describes the novelty of the package and makes for a nice package sticker theme - a mixtape of clocks or a DJ mixer with clocks :clock1: :notes:
